language: rust
rust:
  - nightly
  - 1.36.0

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

// deps
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev

cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all