language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  # deps
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev

  # tool
  - if [[ "$TRAVIS_RUST_VERSION" = "nightly" ]];
    then rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy;
    else rustup component add clippy;
    fi
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

cache: cargo
script:
  -|
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo --only nightly doc
  - cargo clippy

after_success:
  - travis-cargo --only nightly doc-upload
