[package]
name = "nesnes"
version = "0.1.0"
authors = ["yufrice <yufyuf@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.32.2", default_features = false, features = ["unsafe_textures", "ttf"]}
log = "0.4.0"
env_logger = "0.6.1"
